# Generated by Django 6.1.1 on 2026-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='název')),
                ('is_active', models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějakou položku zpracování nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Kč/hod. Ve Strojích se násobí motohodinami. Prázdné = stroj se po hodinách neúčtuje.', max_digits=10, null=True, verbose_name='hodinová sazba')),
                ('rate_per_ton', models.DecimalField(blank=True, decimal_places=2, help_text='Kč za tunu zpracovaného materiálu. Ve Strojích se násobí tunami. Prázdné = stroj se po tunách neúčtuje.', max_digits=10, null=True, verbose_name='cena za tunu')),
            ],
            options={
                'verbose_name': 'stroj',
                'verbose_name_plural': 'stroje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='kód (SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='název')),
                ('is_active', models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějakou položku zpracování nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'materiál',
                'verbose_name_plural': 'materiály',
                'ordering': ['name'],
            },
        ),
    ]
