# Generated by Django 6.1.1 on 2026-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='kód (SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='název')),
                ('is_active', models.BooleanField(default=True, help_text='Odškrtnutím materiál vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má materiál nějakou položku zpracování, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'materiál',
                'verbose_name_plural': 'materiály',
                'ordering': ['name'],
            },
        ),
    ]
