# Generated by Django 6.1 on 2026-08-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kč/hour, for reference only.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='track_stock',
            field=models.BooleanField(default=True, help_text="If off, this material can be shipped/consumed/decreased without a stock-sufficiency check (e.g. an on-site resource like excavated soil that's never formally received)."),
        ),
    ]
