# Generated by Django 6.1 on 2026-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_machine_hourly_rate_material_track_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck to retire instead of deleting — it disappears from every form's dropdown (Receive/Ship/Adjust/Transform) but keeps its history. Deleting is blocked once it has any stock movement or usage history, precisely so that history can't vanish."),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck to retire instead of deleting — it disappears from every form's dropdown (Receive/Ship/Adjust/Transform) but keeps its history. Deleting is blocked once it has any stock movement or usage history, precisely so that history can't vanish."),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck to retire instead of deleting — it disappears from every form's dropdown (Receive/Ship/Adjust/Transform) but keeps its history. Deleting is blocked once it has any stock movement or usage history, precisely so that history can't vanish."),
        ),
    ]
