# Generated by Django 6.1 on 2026-08-26 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_location_is_active_alter_machine_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'lokalita', 'verbose_name_plural': 'lokality'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'stroj', 'verbose_name_plural': 'stroje'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'materiál', 'verbose_name_plural': 'materiály'},
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve všech formulářích (Příjem/Výdej/Úprava/Zpracování), ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějaký skladový pohyb nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kč/hod, pouze pro orientaci.', max_digits=10, null=True, verbose_name='hodinová sazba'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve všech formulářích (Příjem/Výdej/Úprava/Zpracování), ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějaký skladový pohyb nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='motohodiny celkem'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='kategorie'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve všech formulářích (Příjem/Výdej/Úprava/Zpracování), ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějaký skladový pohyb nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='kód (SKU)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Pokud je vypnuto, lze tento materiál vydat/spotřebovat/snížit bez kontroly dostatku zásoby (např. zdroj přímo na místě, jako je vytěžená zemina, který se nikdy formálně nepřijímá).', verbose_name='sledovat zásobu'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_of_measure',
            field=models.CharField(help_text='např. kg, m, ks, t', max_length=20, verbose_name='měrná jednotka'),
        ),
    ]
