# Generated by Django 6.1 on 2026-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_location_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='track_stock',
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějakou položku zpracování nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějakou položku zpracování nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Odškrtnutím záznam vyřadíte místo smazání — zmizí z nabídek ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile má záznam nějakou položku zpracování nebo využití, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní'),
        ),
    ]
