# Generated by Django 6.1 on 2026-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_material_track_stock_alter_location_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='rate_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kč za tunu zpracovaného materiálu, pouze pro orientaci.', max_digits=10, null=True, verbose_name='cena za tunu'),
        ),
    ]
