# Generated by Django 6.1 on 2026-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_remove_machine_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kč/hod. Ve Strojích se násobí motohodinami. Prázdné = stroj se po hodinách neúčtuje.', max_digits=10, null=True, verbose_name='hodinová sazba'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='rate_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kč za tunu zpracovaného materiálu. Ve Strojích se násobí tunami. Prázdné = stroj se po tunách neúčtuje.', max_digits=10, null=True, verbose_name='cena za tunu'),
        ),
    ]
