# Generated by Django 6.1 on 2026-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('WORKER', 'Pracovník'), ('MANAGER', 'Vedoucí'), ('ADMIN', 'Správce')], default='WORKER', max_length=20, verbose_name='role'),
        ),
    ]
