# Generated by Django 6.1 on 2026-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Příjem'), ('SHIPMENT', 'Výdej'), ('TRANSFORM_CONSUME', 'Zpracování – spotřeba'), ('TRANSFORM_PRODUCE', 'Zpracování – výroba'), ('ADJUSTMENT', 'Ruční úprava')], max_length=20),
        ),
    ]
