# Generated by Django 6.1 on 2026-08-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type'),
        ('materials', '0005_alter_location_options_alter_machine_options_and_more'),
        ('workorders', '0006_alter_machineusage_options_alter_workerhours_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'skladový pohyb', 'verbose_name_plural': 'skladové pohyby'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='materials.location', verbose_name='lokalita'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='materials.material', verbose_name='materiál'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Příjem'), ('SHIPMENT', 'Výdej'), ('TRANSFORM_CONSUME', 'Zpracování – spotřeba'), ('TRANSFORM_PRODUCE', 'Zpracování – výroba'), ('ADJUSTMENT', 'Ruční úprava')], max_length=20, verbose_name='typ pohybu'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='poznámka'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Množství se znaménkem: kladné pro příjem na sklad, záporné pro výdej ze skladu.', max_digits=12, verbose_name='množství'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='workorders.workorder', verbose_name='zakázka'),
        ),
    ]
