# Generated by Django 6.1 on 2026-08-26 18:45

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_recorded_at(apps, schema_editor):
    """Rows written before back-dating existed were recorded when they were
    created, so `created_at` is their true entry time — better than the
    migration's run time, which is what the one-off default leaves behind."""
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockMovement.objects.update(recorded_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='zaznamenáno'),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_recorded_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datum a čas pohybu'),
        ),
    ]
