# Generated by Django 6.1 on 2026-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'položka zpracování', 'verbose_name_plural': 'položky zpracování'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('TRANSFORM_CONSUME', 'Zpracování – spotřeba'), ('TRANSFORM_PRODUCE', 'Zpracování – výroba')], max_length=20, verbose_name='typ pohybu'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Množství se znaménkem: kladné pro vyrobený materiál, záporné pro spotřebovaný.', max_digits=12, verbose_name='množství'),
        ),
    ]
