"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-m$#m4d@5-56f+y6cs#3f5yi-$1%-vl#o0uy^=fiw2w5z9ek^wj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Empty by default, and it stays empty for the planned LAN deployment: over
# plain HTTP Django compares the request's `Origin` against its own host, so
# `ALLOWED_HOSTS` alone is enough. It is needed the moment something terminates
# TLS in front of Django -- a tunnel (localtunnel, Cloudflare Tunnel, ngrok) or
# a reverse proxy. The browser then sends `Origin: https://<host>` while Django,
# reached over plain HTTP, expects `http://<host>`, and every POST fails CSRF
# with "Origin checking failed". Entries must carry the scheme, and may use a
# leading wildcard: `https://*.loca.lt`.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# HTTPS. Only the public deployment turns any of this on; see DEPLOYMENT.md.
#
# Everything below defaults to *off*, and that is not laziness — it is the same
# trap STATICFILES_BACKEND carries further down, for the same reason. Django's
# test runner forces DEBUG=False, so a hardcoded `SECURE_SSL_REDIRECT = True`
# would turn every `self.client.get()` in the suite into a 301 and fail
# essentially every test in the project. Production opts in through
# `.env.production`; dev, CI and `runserver` never see these.
#
# SECURE_PROXY_SSL_HEADER is the one exception, set unconditionally, because it
# does nothing at all unless an `X-Forwarded-Proto` header is actually present.
# It is only *safe* because of two things that must stay true together:
# docker-compose.prod.yml publishes no host port for `web`, so the proxy is the
# only thing that can reach gunicorn; and Caddy overwrites that header on every
# request rather than passing a client's through. Re-publish the web port and
# this becomes a forgeable "pretend I am on HTTPS" switch — which is exactly why
# docs/configuration.md tells you *not* to set it on a `runserver` behind a dev
# tunnel, where anyone can send the header directly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# One variable drives both cookies deliberately. No deployment wants one and not
# the other, and a half-set pair fails as "login works but every form comes back
# 403" — which reads like a CSRF bug and sends you looking in the wrong file.
SESSION_COOKIE_SECURE = config('SECURE_COOKIES', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('SECURE_COOKIES', default=False, cast=bool)

# HSTS tells a browser to refuse plain HTTP for this host until the max-age
# expires. It is the one setting here that cannot be walked back by editing a
# file: a browser that has seen the header keeps honouring it for the full
# duration no matter what the server later sends. Hence a deliberately short
# starting value in .env.production.example, raised once renewal has survived a
# cycle.
#
# INCLUDE_SUBDOMAINS is safe on a *subdomain* deployment (it covers
# `inventar.firma.cz` and anything under it, and does not propagate upward to
# `firma.cz`). Deploy at the apex instead and it commits the company's every
# other subdomain to HTTPS — read that as a policy decision, not a checkbox.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)

# Left off, and `manage.py check --deploy` will say so (W021). Preloading means
# submitting the domain to a list compiled into browsers themselves; removal
# takes months and reaches users only as they update. It is a decision about the
# company's domain, not about this app. See step 12 of DEPLOYMENT.md.
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'materials',
    # Holds no code — only its migrations. `StockMovement` moved to `workorders`
    # (state-only, `inventory.0008` / `workorders.0013`), but the app has to stay
    # installed: `materials.0008` depends on `inventory.0006`, and Django cannot
    # resolve a dependency on an app it does not know about. Removing this line
    # breaks `migrate` on a fresh database.
    'inventory',
    'workorders',
    # Login rate limiting. The app is on the public internet and Django ships
    # nothing for this; see the AXES_* block below for the policy and
    # DEPLOYMENT.md for how to unlock an account.
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Last, and it has to be: it inspects the *response* from the login view and
    # swaps in the lockout page when the backend flagged the request. It also
    # needs the session and auth middleware above it to have run.
    'axes.middleware.AxesMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

# `AxesStandaloneBackend` must come first — it does not authenticate anybody, it
# only refuses a request that is already locked out, and returning `None` lets
# `ModelBackend` behind it do the real work.
#
# It deliberately does *not* subclass `ModelBackend` and defines no `get_user`.
# That is what keeps the test suite working: `Client.force_login()` picks the
# first backend that *has* a `get_user`, so all ~130 `force_login` calls in the
# suite resolve to `ModelBackend` and never touch axes. (`Client.login()` would
# be a different story — it calls `authenticate()` with no request, which axes
# rejects outright. There is not one `client.login()` in this project; keep it
# that way.)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'transform_create'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='materialinventory'),
        'USER': config('DB_USER', default='materialinventory'),
        'PASSWORD': config('DB_PASSWORD', default='materialinventory'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# django-axes — login rate limiting.
#
# Django ships nothing for this, and the LAN deployment did not need it: an
# attacker had to be in the building. On a public domain the login form takes
# unlimited silent guesses against every seeded account, so this is the one
# thing the old perimeter was doing that had to be replaced with code.

# Lock the *account*, not the address. This is the important choice here and the
# default (`['ip_address']`) would have been actively harmful: depot staff reach
# the app from a handful of shared egress addresses — the office NAT, a mobile
# carrier — and behind the reverse proxy every request that axes has not been
# told about looks like it came from the proxy container. Locking by IP would
# therefore let one worker mistyping their password lock out the whole depot,
# while barely inconveniencing an attacker with a list of addresses.
#
# The trade-off is real and worth knowing: someone who learns a username can
# lock that person out on purpose. That is a nuisance bounded by the cool-off
# below, and it is the cheaper of the two failure modes.
AXES_LOCKOUT_PARAMETERS = ['username']

# Five, not the library's default of three. These are phone keyboards, Czech
# passwords and gloved hands; three is a support call waiting to happen.
AXES_FAILURE_LIMIT = 5

# Long enough to make guessing pointless, short enough that a locked-out worker
# is not finished for the shift. An admin can clear it immediately — see the
# `axes_reset_username` command in DEPLOYMENT.md.
#
# `templates/registration/lockout.html` quotes this figure in Czech prose
# ("přibližně za 30 minut"), because a worker who cannot tell 5 minutes from 5
# hours just phones their manager. The lockout context does carry the value, but
# only as a `timedelta` that renders "0:30:00". **Change both together.**
AXES_COOLOFF_TIME = timedelta(minutes=30)

# A correct password clears the counter, so four typos over a week do not add up
# to a lockout on a fifth unrelated day.
AXES_RESET_ON_SUCCESS = True

# Czech, like every other user-facing string in this project, and hardcoded for
# the same reason (see CLAUDE.md — app copy does not go through i18n).
AXES_LOCKOUT_TEMPLATE = 'registration/lockout.html'
AXES_COOLOFF_MESSAGE = 'Účet je dočasně uzamčen po opakovaných neúspěšných přihlášeních. Zkuste to prosím později.'
AXES_PERMALOCK_MESSAGE = 'Účet je uzamčen po opakovaných neúspěšných přihlášeních. Obraťte se na správce.'

# Axes ships catalogs for ar/de/fa/fr/id/pl/ru/tr and **no Czech**, so its admin
# section and both its models would render English — the only English in an
# admin this project keeps Czech through three separate mechanisms. The attempts
# are still recorded; they are read with `manage.py axes_list_attempts`.
# `AdminIndexTests` in accounts/tests.py asserts the section stays out.
AXES_ENABLE_ADMIN = False

# Which address to record. Behind Caddy, `REMOTE_ADDR` is the proxy container
# and the client is in `X-Forwarded-For`, so without this every attempt in the
# log is attributed to the proxy and the log tells you nothing about where the
# guessing came from. It does not affect *who* gets locked out — that is the
# username — which is why getting it wrong is a lost audit trail rather than an
# outage.
#
# Off by default because there is no proxy in dev, in CI or under `runserver`,
# and trusting `X-Forwarded-For` where anything can reach Django directly means
# trusting a header the client wrote.
BEHIND_PROXY = config('BEHIND_PROXY', default=False, cast=bool)
if BEHIND_PROXY:
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Czech locale. App copy is hardcoded Czech (see CLAUDE.md) — this setting is
# what makes Django's *own* strings Czech too: admin chrome, auth, and form
# validation errors ("Toto pole je vyžadováno." instead of "This field is
# required."). LocaleMiddleware is deliberately not installed, so the language
# is fixed rather than negotiated from the browser's Accept-Language.
LANGUAGE_CODE = 'cs'

# Czech overrides for the handful of *Django* strings whose `cs` translation
# Django doesn't ship (the admin's delete confirmation, the date-hierarchy
# label, `- Select an option -`, ...). LOCALE_PATHS is searched ahead of the
# app catalogs, so entries here win. See locale/cs/LC_MESSAGES/django.po — the
# runtime reads the compiled .mo next to it, so edits need `compilemessages`.
LOCALE_PATHS = [BASE_DIR / 'locale']

# Depot-local time. USE_TZ keeps everything stored as UTC; this only affects
# how datetimes render. No filter depends on it: the date filters compare
# `WorkOrder.performed_on`, a `DateField` with no time and no zone.
TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 5.1 removed STATICFILES_STORAGE; the backend lives in STORAGES now, so
# the old setting sat here being silently ignored (see DEPLOYMENT_PLAN.md).
#
# The default stays the plain backend on purpose. Whitenoise's manifest storage
# rewrites every {% static %} URL to a hashed filename looked up in the
# `staticfiles.json` that `collectstatic` writes, and with no manifest on disk
# it raises instead of falling back. Django's test runner forces DEBUG=False,
# and DEBUG is exactly what makes the hashing short-circuit — so defaulting to
# manifest storage would make `manage.py test` fail on every template that
# renders a {% static %} tag until someone remembered to run collectstatic.
#
# Production opts in via STATICFILES_BACKEND instead. The Dockerfile sets it as
# an ENV, which covers both the collectstatic build step and the running
# container, so an image can never serve a manifest it didn't write.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': config('STATICFILES_BACKEND', default='django.contrib.staticfiles.storage.StaticFilesStorage'),
    },
}

# Django's own default routes `django.request` errors to `mail_admins` (which
# only fires when DEBUG=False) and gives its console handler a
# `require_debug_true` filter. With ADMINS empty and no mail backend — the state
# of this project — that means an unhandled 500 in production is recorded
# *nowhere*: gunicorn sees an ordinary response come back, so `docker compose
# logs web` stays silent and a report from the depot starts with no traceback.
#
# One stdout handler is the whole fix; Docker captures stdout, and
# docker-compose.prod.yml rotates it.
#
# ERROR rather than WARNING on purpose: `django.request` logs every 4xx at
# WARNING, and the suite asserts a pile of 403s from `role_required` — at
# WARNING those would spray through the test output.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
