"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-m$#m4d@5-56f+y6cs#3f5yi-$1%-vl#o0uy^=fiw2w5z9ek^wj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_htmx',
    'widget_tweaks',
    'accounts',
    'materials',
    'inventory',
    'workorders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='materialinventory'),
        'USER': config('DB_USER', default='materialinventory'),
        'PASSWORD': config('DB_PASSWORD', default='materialinventory'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Czech locale. App copy is hardcoded Czech (see CLAUDE.md) — this setting is
# what makes Django's *own* strings Czech too: admin chrome, auth, and form
# validation errors ("Toto pole je vyžadováno." instead of "This field is
# required."). LocaleMiddleware is deliberately not installed, so the language
# is fixed rather than negotiated from the browser's Accept-Language.
LANGUAGE_CODE = 'cs'

# Czech overrides for the handful of *Django* strings whose `cs` translation
# Django doesn't ship (the admin's delete confirmation, the date-hierarchy
# label, `- Select an option -`, ...). LOCALE_PATHS is searched ahead of the
# app catalogs, so entries here win. See locale/cs/LC_MESSAGES/django.po — the
# runtime reads the compiled .mo next to it, so edits need `compilemessages`.
LOCALE_PATHS = [BASE_DIR / 'locale']

# Depot-local time. USE_TZ keeps everything stored as UTC; this only affects
# how datetimes render and how `__date` lookups (the history date filters) pick
# their day boundaries.
TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 5.1 removed STATICFILES_STORAGE; the backend lives in STORAGES now, so
# the old setting sat here being silently ignored (see DEPLOYMENT_PLAN.md).
#
# The default stays the plain backend on purpose. Whitenoise's manifest storage
# rewrites every {% static %} URL to a hashed filename looked up in the
# `staticfiles.json` that `collectstatic` writes, and with no manifest on disk
# it raises instead of falling back. Django's test runner forces DEBUG=False,
# and DEBUG is exactly what makes the hashing short-circuit — so defaulting to
# manifest storage would make `manage.py test` fail on every template that
# renders a {% static %} tag until someone remembered to run collectstatic.
#
# Production opts in via STATICFILES_BACKEND instead. The Dockerfile sets it as
# an ENV, which covers both the collectstatic build step and the running
# container, so an image can never serve a manifest it didn't write.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': config('STATICFILES_BACKEND', default='django.contrib.staticfiles.storage.StaticFilesStorage'),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
