# Generated by Django 6.1.1 on 2026-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='název')),
                ('is_active', models.BooleanField(default=True, help_text='Odškrtnutím lokaci vyřadíte místo smazání — zmizí z nabídky ve formuláři Zpracování, ale historie zůstane zachována. Smazání je zablokováno, jakmile lokaci nese nějaké zpracování, právě proto, aby historie nemohla zmizet.', verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'lokace',
                'verbose_name_plural': 'lokace',
                'ordering': ['name'],
            },
        ),
    ]
