# Generated by Django 6.1.1 on 2026-09-12 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('performed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='datum provedení')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='popis')),
                ('status', models.CharField(choices=[('PENDING', 'Čeká na schválení'), ('APPROVED', 'Schváleno')], default='PENDING', max_length=20, verbose_name='stav')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='posouzeno')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='spolupracovníci')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='posoudil')),
            ],
            options={
                'verbose_name': 'zakázka',
                'verbose_name_plural': 'zakázky',
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='motohodiny')),
                ('tons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='odpracované tuny')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='materials.machine', verbose_name='stroj')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usages', to='workorders.workorder', verbose_name='zakázka')),
            ],
            options={
                'verbose_name': 'využití stroje',
                'verbose_name_plural': 'využití strojů',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='hodiny')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worked_hours', to=settings.AUTH_USER_MODEL, verbose_name='pracovník')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_hours', to='workorders.workorder', verbose_name='zakázka')),
            ],
            options={
                'verbose_name': 'odpracované hodiny',
                'verbose_name_plural': 'odpracované hodiny',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('work_order', 'user'), name='unique_worker_hours_per_work_order')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('TRANSFORM_CONSUME', 'Zpracování – spotřeba'), ('TRANSFORM_PRODUCE', 'Zpracování – výroba')], max_length=20, verbose_name='typ pohybu')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Množství se znaménkem: kladné pro vyrobený materiál, záporné pro spotřebovaný.', max_digits=12, verbose_name='množství')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='materials.material', verbose_name='materiál')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='workorders.workorder', verbose_name='zakázka')),
            ],
            options={
                'verbose_name': 'položka zpracování',
                'verbose_name_plural': 'položky zpracování',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['material'], name='workorders__materia_0f7333_idx')],
            },
        ),
    ]
