# Generated by Django 6.1 on 2026-08-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_machine'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='materials.machine')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usages', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
