# Generated by Django 6.1.1 on 2026-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='poznámky'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.CharField(max_length=255, verbose_name='popis'),
        ),
    ]
