# Generated by Django 6.1 on 2026-08-08 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_machineusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
