# Generated by Django 6.1.1 on 2026-09-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('workorders', '0002_workorder_notes_alter_workorder_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRefuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='natankované litry')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuels', to='machines.machine', verbose_name='stroj')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_refuels', to='workorders.workorder', verbose_name='zakázka')),
            ],
            options={
                'verbose_name': 'tankování',
                'verbose_name_plural': 'tankování',
                'ordering': ['-id'],
            },
        ),
    ]
