# Generated by Django 6.1.1 on 2026-09-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('workorders', '0003_machinerefuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='locations.location', verbose_name='lokace'),
        ),
    ]
