# Generated by Django 6.1.1 on 2026-09-22 18:46

import workorders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='photo',
            field=models.FileField(blank=True, upload_to=workorders.models.job_photo_path, verbose_name='fotka'),
        ),
    ]
