# Generated by Django 6.1.1 on 2026-10-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineusage',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='motohodiny'),
        ),
    ]
