# Generated by Django 6.1 on 2026-08-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_location_options_alter_machine_options_and_more'),
        ('workorders', '0005_backfill_worker_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineusage',
            options={'ordering': ['-created_at'], 'verbose_name': 'využití stroje', 'verbose_name_plural': 'využití strojů'},
        ),
        migrations.AlterModelOptions(
            name='workerhours',
            options={'ordering': ['user__username'], 'verbose_name': 'odpracované hodiny', 'verbose_name_plural': 'odpracované hodiny'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'zakázka', 'verbose_name_plural': 'zakázky'},
        ),
        migrations.AlterField(
            model_name='machineusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='machineusage',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='motohodiny'),
        ),
        migrations.AlterField(
            model_name='machineusage',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='materials.machine', verbose_name='stroj'),
        ),
        migrations.AlterField(
            model_name='machineusage',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usages', to='workorders.workorder', verbose_name='zakázka'),
        ),
        migrations.AlterField(
            model_name='workerhours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='workerhours',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='hodiny'),
        ),
        migrations.AlterField(
            model_name='workerhours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worked_hours', to=settings.AUTH_USER_MODEL, verbose_name='pracovník'),
        ),
        migrations.AlterField(
            model_name='workerhours',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_hours', to='workorders.workorder', verbose_name='zakázka'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='spolupracovníci'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='popis'),
        ),
    ]
