# Generated by Django 6.1 on 2026-09-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_alter_machineusage_options_alter_workerhours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineusage',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='odpracované tuny'),
        ),
    ]
