# Generated by Django 6.1 on 2026-09-01 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def approve_existing(apps, schema_editor):
    """Every job recorded before approval existed was already counted by the
    Hodiny and Stroje pages, and those pages now show approved jobs only.
    Leaving them PENDING would make the whole history disappear, so they are
    approved as of their own creation, with no reviewer — nobody signed them."""
    WorkOrder = apps.get_model('workorders', 'WorkOrder')
    WorkOrder.objects.update(status='APPROVED', reviewed_at=F('created_at'), reviewed_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_machineusage_tons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='review_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='poznámka k posouzení'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='posouzeno'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='posoudil'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Čeká na schválení'), ('APPROVED', 'Schváleno'), ('RETURNED', 'Vráceno k přepracování')], default='PENDING', max_length=20, verbose_name='stav'),
        ),
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
